package com.jj.base.utils;

public class RouterMap {
    public static final int NEED_LOGIN = 1001;
    public static final int NEED_PAY = 1002;

    public static final String COMIC_DETAIL_ACTIVITY = "/ui/ComicDetailActivity";
    public static final String COMIC_MAIN_ACTIVITY = "/app/activity/MainActivity";
    public static final String COMIC_TYPELIST_ACTIVITY = "/ui/recommend_list/TypeListActivity";
    public static final String COMIC_RICHMANRANK_ACTIVITY = "/ui/featured/RichManRankActivity";
    public static final String COMIC_READ_COMIC_ACTIVITY = "/ui/ReadComicActivity";
    public static final String COMIC_LOGIN_ACTIVITY = "/ui/LoginActivity";
    public static final String COMIC_REGISTER_ACTIVITY = "/ui/RegisterActivity";
    public static final String COMIC_SETTING_ACTIVITY = "/ui/SettingActivity";
    public static final String COMIC_SEARCH_ACTIVITY = "/ui/recommend_list/SearchActivity";
    public static final String COMIC_SEARCH_RESULT_ACTIVITY = "/ui/recommend_list/SearchResultActivity";
    public static final String COMIC_RECHARGE_RECORD_ACTIVITY = "/ui/mine/RechargeRecordActivity";
    public static final String COMIC_NEW_RECHARGE_RECORD_ACTIVITY = "/ui/mine/NewRechargeRecordActivity";
    public static final String COMIC_PAY_RECORD_ACTIVITY = "/ui/mine/PayRecordActivity";
    public static final String COMIC_WEB_ACTIVITY = "/ui/web/WebActivity";
    public static final String COMIC_WEBVIEW_ACTIVITY = "/ui/web/WebViewActivity";
    public static final String COMIC_PAY_ACTIVITY = "/ui/mine/PayActivity";
    public static final String COMIC_VIP_ACTIVITY = "/ui/mine/VIPActivity";
    public static final String COMIC_GOLD_CENTER_ACTIVITY = "/ui/mine/GoldCenterActivity";
    public static final String COMIC_FREE_LIST_ACTIVITY = "/ui/featured/FreeListActivity";
    public static final String COMIC_REWARD_ACTIVITY = "/ui/mine/rEWARDActivity";
    public static final String COMIC_SUBSCRIBE_ACTIVITY = "/ui/SubscribeActivity";
    public static final String COMIC_RECOMMEND_FRAGMENT = "/comic/recommend_list/RecommendFragment";
    public static final String COMIC_RECOMMEND_LOADMORE = "/ui/featured/RecommendLoadMoreActovity";
    public static final String COMIC_HOME_FRAGMENT = "/comic/recommend_list/HomeFragment";
    public static final String COMIC_FIND_FRAGMENT = "/comic/classify/FindBookFragment";
    public static final String COMIC_SEARCH_FRAGMENT = "/comic/money/SearchFragment";
    public static final String COMIC_BOOKSHELF_FRAGMENT = "/comic/bookshelf/BookShelfFragment";
    public static final String COMIC_MINE_FRAGMENT = "/comic/mine/MineFragment";
    public static final String COMIC_DETAIL_FRAGMENT = "/comic/detail/ComicDetailFragment";
    public static final String COMIC_RECENTLY_FRAGMENT = "/comic/recommend_list/RecentlyFragment";
    public static final String COMIC_BEST_SALE_FRAGMENT = "/comic/list/BestSaleFragment";
    public static final String COMIC_MOST_REWARD_FRAGMENT = "/comic/list/MostRewardFragment";
    public static final String COMIC_NEW_BOOK_FRAGMENT = "/comic/list/NewBookFragment";
    public static final String COMIC_POPULARITY_FRAGMENT = "/comic/list/PopularityFragment";
    public static final String COMIC_OTAKU_FRAGMENT = "/comic/list/OtakuFragment";
    public static final String COMIC_LIST_FRAGMENT = "/comic/list/ListFragment";
    public static final String COMIC_RANK_ACTIVITY = "/comic/list/RankActivity";
    public static final String COMIC_COMMENTlIST_ACTIVITY = "/ui/detail/CommentListActicity";
    public static final String COMIC_ABOUT_ACTIVITY = "/ui/AboutActicity";
    public static final String COMIC_FEEDBACK_ACTIVITY = "/ui/mine/FeedbackActivity";
    public static final String COMIC_MYFEEDBACK_ACTIVITY = "/ui/mine/MyFeedbackActivity";
    public static final String COMIC_KEFU_ACTIVITY = "/ui/mine/KefuActivity";
    public static final String COMIC_EDIT_USER_INFO_ACTIVITY = "/ui/mine/EditUserInfoActivity";
    public static final String COMIC_CHECK_USER_INFO_ACTIVITY = "/ui/mine/CheckUserInfoActivity";
    public static final String COMIC_BIND_PHONE_ACTIVITY = "/ui/mine/BindPhoneActivity";
    public static final String COMIC_COUPON_CODE_ACTIVITY = "/ui/mine/CouponCodeActivity";
    public static final String COMIC_AGREEMENT_ACTIVITY = "/ui/mine/UserAgreementActivity";
    public static final String COMIC_NOTIFICATION_ACTIVITY = "/ui/mine/NotificationActivity";
}
